### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by scarlightning** [Jezza/Thaumic-Pipes#13]
I've noticed that when using the pipes with the essentia reservoir, the alchemical furnace will fill the reservoirs up, but an alchemical construct is unable to remove the essentia from the reservoirs for use. I've checked my piping and set up at least 10 times and everything is fine. I then replaced the reservoirs with warded jars and the system worked, so its the reservoirs. Also, reservoirs are only able to have one pipe connected to them at a time, compared to jars.

As for the alchemical construct, I've also noticed that the construct will draw essentia from the jars when a recipe is selected, even if there is no catalyst and the machine is not functioning.

I also had my server crash on me, and I'm unsure why. I'm not very good at reading errors, but I do know the error was a ticking block entity. When I teleported to the location of the error, it was a thaumic pipe, which I then broke. As of now, after breaking the pipe, my server has not crashed yet, so I do believe that it was the pipe. I will paste the error for you to read. Not sure what was going on, but I hope all this I've given you helps. Sorry if you wanted each of these errors in separate issues, if I find anything else and you want I'll separate each issue.

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 4/10/15 8:34 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at me.jezza.oc.api.network.NetworkCore.postMessage(NetworkCore.java:140)
	at me.jezza.thaumicpipes.common.multipart.pipe.thaumic.ThaumicPipePart.processStorage(ThaumicPipePart.java:171)
	at me.jezza.thaumicpipes.common.multipart.pipe.thaumic.ThaumicPipePart.update(ThaumicPipePart.java:123)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76)
	at codechicken.multipart.TileMultipart.func_145845_h(TileMultipart.scala:82)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at me.jezza.oc.api.network.NetworkCore.postMessage(NetworkCore.java:140)
	at me.jezza.thaumicpipes.common.multipart.pipe.thaumic.ThaumicPipePart.processStorage(ThaumicPipePart.java:171)
	at me.jezza.thaumicpipes.common.multipart.pipe.thaumic.ThaumicPipePart.update(ThaumicPipePart.java:123)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76)
	at codechicken.multipart.TileMultipart.func_145845_h(TileMultipart.scala:82)

-- Block entity being ticked --
Details:
	Name: savedMultipart // TileMultipart_cmp$$2
	Block type: ID #530 (tile.multipart // codechicken.multipart.BlockMultipart)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-425,71,344), Chunk: (at 7,4,8 in -27,21; contains blocks -432,0,336 to -417,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #530 (tile.multipart // codechicken.multipart.BlockMultipart)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['ninjabunny21'/196, l='world', x=-354.35, y=64.00, z=156.19]]
	Chunk stats: ServerChunkCache: 686 Drop: 0
	Level seed: -3204062629075621679
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-144,64,248), Chunk: (at 0,4,8 in -9,15; contains blocks -144,0,240 to -129,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3612544 game time, 3900632 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 12019 (now: true), thunder time: 102130 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 2.6.32-504.3.3.el6.x86_64
	Java Version: 1.7.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 215719160 bytes (205 MB) / 518979584 bytes (494 MB) up to 518979584 bytes (494 MB)
	JVM Flags: 5 total; -Xmx512M -Xms512M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 26 mods loaded, 26 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (custom.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (custom.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.4.8} [BuildCraft] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.4.8} [BC Transport] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.4.8} [BC Silicon] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.4.8} [BC Builders] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.4.8} [BC Energy] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.4.8} [BC Factory] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	props{1.12} [Decocraft] (Decocraft-v1.12b_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OmnisCore{0.1.0} [Omnis Core] (OmnisCore-1.7.10 - 0.0.6-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	punt{1.7.10-10.13.0-14.0} [Punt] (Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	whitehall{1.7.10-10.13.0-14.0} [Whitehall] (Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	hoy{1.7.10-10.13.0-14.0} [Hoy] (Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	smallboats{1.7.10-10.13.0-14.0} [SmallBoats (base)] (Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicPipes{1.2.00} [Thaumic Pipes] (ThaumicPipes-1.7.10 - 1.2.1b-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TravellersGear{1.15.7} [Traveller's Gear] (TravellersGear-1.7.10-1.15.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.5} [The Twilight Forest] (twilightforest-1.7.10-2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 12; [EntityPlayerMP['ninjabunny21'/196, l='world', x=-354.35, y=64.00, z=156.19]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Jezza** [comment]
Oh, wow, I'm so sorry. I didn't even see this.  
I apologise for the lack of response. 
Currently, I have no computer, but I'll look into it when it gets here.

**Comment by Urkaz** [comment]
I'm having the same error. WhenI leave my house where the pipes are, the server crashes with the same crash report pasted by scarlightning.
